/*
방명록
글번호, 아이디, 비번, 내용, 조회수,
NO, ID, PASSWORD, CONTENT, READCOUNT, BNUM, LVL, STEP, NREF

, READCOUNT NUMBER(5, 0) NOT NULL 
, BNUM NUMBER(5, 0) NOT NULL  
, LVL NUMBER(5, 0) NOT NULL   
, STEP NUMBER(5, 0) NOT NULL  
, NREF NUMBER(5, 0) NOT NULL 
*/

-- TABLE guestbook
CREATE TABLE GUESTBOOK
(
GB_NO NUMBER(15,0) PRIMARY KEY
, GB_ID VARCHAR2(15) NOT NULL
, GB_PASS VARCHAR2(15) NOT NULL
, GB_CON VARCHAR2(1000)
, GB_DATE DATE DEFAULT SYSDATE
, READCOUNT NUMBER(5, 0) NOT NULL
, BNUM NUMBER(5, 0) NOT NULL
, LVL NUMBER(5, 0) NOT NULL
, STEP NUMBER(5, 0) NOT NULL
, NREF NUMBER(5, 0) NOT NULL
);

-- PACKAGE
create or replace PACKAGE PKG_GUESTBOOK AS

PROCEDURE PROC_GB_LIST( O_CUR OUT SYS_REFCURSOR );

PROCEDURE PROC_GB_DELETE( DE_GB_NO IN NUMBER, DE_GB_PASS IN VARCHAR2 );

PROCEDURE PROC_GB_UPDATE( UP_GB_CON IN VARCHAR2, UP_GB_NO IN NUMBER, UP_GB_PASS IN VARCHAR2 );

PROCEDURE PROC_GB_VIEW (
IN_GB_NO IN NUMBER
, O_CUR OUT SYS_REFCURSOR
);

PROCEDURE PROC_GB_INSERT(
IN_GB_ID IN VARCHAR2
, IN_GB_PASS IN VARCHAR2
, IN_GB_CON IN VARCHAR2
, IN_BNUM IN NUMBER
, IN_LVL IN NUMBER
, IN_STEP IN NUMBER
, IN_NREF IN NUMBER
);

END PKG_GUESTBOOK;

-- PACKAGE BODY
create or replace PACKAGE BODY PKG_GUESTBOOK AS

PROCEDURE PROC_GB_LIST(
O_CUR OUT SYS_REFCURSOR
) AS
BEGIN
OPEN O_CUR FOR
SELECT
GB_NO
, GB_ID
, GB_PASS
, GB_CON
, GB_DATE
, READCOUNT
, BNUM
, LVL
, STEP
, NREF
FROM GUESTBOOK
ORDER BY BNUM DESC, LVL ASC;
END PROC_GB_LIST;

PROCEDURE PROC_GB_DELETE(
DE_GB_NO IN NUMBER
, DE_GB_PASS IN VARCHAR2
) AS
BEGIN
DELETE FROM GUESTBOOK
WHERE GB_NO = DE_GB_NO AND GB_PASS = DE_GB_PASS;
END PROC_GB_DELETE;

PROCEDURE PROC_GB_UPDATE(
UP_GB_CON IN VARCHAR2
, UP_GB_NO IN NUMBER
, UP_GB_PASS IN VARCHAR2
) AS
BEGIN
UPDATE GUESTBOOK
SET GB_CON = UP_GB_CON
WHERE GB_NO = UP_GB_NO AND GB_PASS = UP_GB_PASS;
END PROC_GB_UPDATE;

PROCEDURE PROC_GB_VIEW (
IN_GB_NO IN NUMBER
, O_CUR OUT SYS_REFCURSOR
) AS
BEGIN
UPDATE GUESTBOOK
SET READCOUNT = READCOUNT + 1
WHERE GB_NO = IN_GB_NO;
COMMIT;

OPEN O_CUR FOR
  SELECT GB_NO
    , GB_ID 
    , GB_PASS 
    , GB_CON 
    , GB_DATE 
    , READCOUNT 
    , BNUM 
    , LVL 
    , STEP 
    , NREF 
  FROM GUESTBOOK
  WHERE GB_NO = IN_GB_NO;
END PROC_GB_VIEW;

PROCEDURE PROC_GB_INSERT(
IN_GB_ID IN VARCHAR2
, IN_GB_PASS IN VARCHAR2
, IN_GB_CON IN VARCHAR2
, IN_BNUM IN NUMBER
, IN_LVL IN NUMBER
, IN_STEP IN NUMBER
, IN_NREF IN NUMBER
) AS
V_GB_NO NUMBER(10);
V_BNUM NUMBER(10);
V_LVL NUMBER(10);
V_STEP NUMBER(10);
V_NREF NUMBER(10);
BEGIN
SELECT NVL(MAX(GB_NO),0) + 1
INTO V_GB_NO
FROM GUESTBOOK;

  IF IN_BNUM = 0 THEN -- 새글
  
  -- 글번호 생성
  SELECT NVL(MAX(BNUM),0) + 1
    INTO V_BNUM
    FROM GUESTBOOK;
    
    V_LVL := 0;
    V_STEP := 0;
    
    SELECT NVL(MAX(NREF),0) + 1
    INTO V_NREF
    FROM GUESTBOOK
    WHERE GB_ID = IN_GB_ID;
    
    ELSE --답글
      V_BNUM := IN_BNUM;
      V_LVL  := IN_LVL + 1;
      
      V_STEP := IN_STEP + 1;
      UPDATE GUESTBOOK
        SET STEP = STEP + 1
        WHERE GB_ID = IN_GB_ID
        AND NREF = IN_NREF
        AND STEP >= V_STEP;
        
    V_NREF := IN_NREF;
END IF;

INSERT INTO GUESTBOOK
(
GB_NO      
, GB_ID   
, GB_PASS  
, GB_CON   
, GB_DATE  
, READCOUNT 
, BNUM 
, LVL  
, STEP 
, NREF
)
VALUES
(
V_GB_NO      
, IN_GB_ID   
, IN_GB_PASS  
, IN_GB_CON   
, SYSDATE 
, 0 
, V_BNUM 
, V_LVL  
, V_STEP 
, V_NREF
);
COMMIT;     
END PROC_GB_INSERT;

END PKG_GUESTBOOK;